name: Deploy Docs

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "vox.gemspec"
      - "CHANGELOG.md"
      - ".rubocop.yml"
      - ".rspec"
      - "Rakefile"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run YARD
        run: bundle exec yard --output-dir docs
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          destination_dir: ${{ steps.extract_branch.outputs.branch }}
